### ISSUE TITLE
Error in Tk Callback

### ISSUE THREAD

**Issue by EAdornado** [arsh09/sentimentanalysiswithgui#1]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "Sentimentanalysis.py", line 111, in main
    tweet_file.write((tweet.text).encode('utf-8'))

**Comment by arsh09** [comment]
It was written on a very old Twitter API. I am sure the API has changed quite a lot. 

To check if the Tk callback works, comment the content of the callback function that raise the error and print out something (just to be sure that it is in fact an API issue rather a TK)
